Total_Meal = float(input("Enter the total meal cost: "))
Tip_Value15 = (Total_Meal * 0.15)
Tip_Value18 = (Total_Meal * 0.18)
Tip_Value20 = (Total_Meal * 0.2)
print("With 15% Tip: \n Total: $" , Total_Meal , "\n Tip: $" , Tip_Value15 , "\n Total + Tip: $" , (Total_Meal + Tip_Value15))
print("\t")
print("With 18% Tip: \n Total: $" , Total_Meal , "\n Tip: $" , Tip_Value18 , "\n Total + Tip: $" , (Total_Meal + Tip_Value18))
print("\t")
print("With 20% Tip: \n Total: $" , Total_Meal , "\n Tip: $" , Tip_Value20 , "\n Total + Tip: $" , (Total_Meal + Tip_Value20))